#!/usr/bin/env python

import sys,os
import xml.dom.minidom

fileName = os.path.join (sys.argv[1],'addon.xml')
xmldoc = xml.dom.minidom.parse( fileName )

# bump version
version = xmldoc.childNodes[0].getAttribute('version')
parts = version.split('.')
parts[-1] = str(int(parts[-1]) + 1)
print 'Addon version bumped to %s' % '.'.join(parts)
xmldoc.childNodes[0].setAttribute('version','.'.join(parts))
for node in xmldoc.childNodes[0].getElementsByTagName('requires')[0].getElementsByTagName('import'):
    dependency = os.path.join (node.getAttribute('addon'),'addon.xml')
    if os.path.exists(dependency):
        ver = xml.dom.minidom.parse(dependency).childNodes[0].getAttribute('version')
        if ver != node.getAttribute('version'):
            node.setAttribute('version',ver)
            print 'Dependency %s to %s' % (node.getAttribute('addon'),ver) 
with open(fileName,'wb') as f:
    f.write(xmldoc.toxml('utf-8'))
